# Week 1 - Data Science with Python

## Python for Data Analysis

## 1. NumPy

### What is NumPy?

NumPy is a Python library used for numerical computing and working with arrays.

It helps us perform mathematical and numerical operations efficiently.

## 1. NumPy

### What is NumPy?

NumPy stands for Numerical Python.

It is a Python library used for numerical computing and working with arrays.

### Why do we use NumPy?

NumPy helps us work with numerical data and perform mathematical operations efficiently.

In [6]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


In [7]:
print(numbers + 10)
print(numbers * 2)

[20 30 40 50 60]
[ 20  40  60  80 100]


### NumPy Array Operations

NumPy allows us to perform mathematical operations directly on arrays.

In [8]:
print(numbers - 5)
print(numbers / 10)

[ 5 15 25 35 45]
[1. 2. 3. 4. 5.]


### NumPy Array Properties

NumPy arrays have useful properties that tell us about the data.

- `ndim` → number of dimensions
- `shape` → size of each dimension
- `size` → total number of elements

In [9]:
print("Dimensions:", numbers.ndim)
print("Shape:", numbers.shape)
print("Size:", numbers.size)

Dimensions: 1
Shape: (5,)
Size: 5


### Accessing Array Elements

We can access individual elements of a NumPy array using their index.

Python indexing starts from `0`.

In [10]:
print("First element:", numbers[0])
print("Third element:", numbers[2])

First element: 10
Third element: 30


### NumPy Array Slicing

Slicing allows us to select a range of elements from an array.

The syntax is:

array[start:stop]

The `stop` index is not included.

In [11]:
print(numbers[1:4])
print(numbers[:3])

[20 30 40]
[10 20 30]


## 2. Pandas

### What is Pandas?

Pandas is a Python library used for data analysis and data manipulation.

It provides useful data structures such as Series and DataFrame.

In [12]:
import pandas as pd

data = {
    "Name": ["Ali", "Ravi", "John", "Sara"],
    "Marks": [85, 78, 92, 88]
}

df = pd.DataFrame(data)

print(df)

   Name  Marks
0   Ali     85
1  Ravi     78
2  John     92
3  Sara     88


### Selecting Data from a DataFrame

We can select a single column from a Pandas DataFrame using its column name.

In [13]:
print(df["Name"])
print(df["Marks"])

0     Ali
1    Ravi
2    John
3    Sara
Name: Name, dtype: object
0    85
1    78
2    92
3    88
Name: Marks, dtype: int64


### Adding a New Column

We can create a new column in a DataFrame by assigning values to a new column name.

In [14]:
df["Result"] = ["Pass", "Pass", "Pass", "Pass"]

print(df)

   Name  Marks Result
0   Ali     85   Pass
1  Ravi     78   Pass
2  John     92   Pass
3  Sara     88   Pass


## 3. Basic Data Cleaning

### Missing Values

Missing values are empty or unavailable values in a dataset.

Before analyzing data, we need to identify and handle missing values.

In [15]:
clean_data = {
    "Name": ["Ali", "Ravi", "John", "Sara"],
    "Marks": [85, None, 92, 88]
}

clean_df = pd.DataFrame(clean_data)

print(clean_df)

   Name  Marks
0   Ali   85.0
1  Ravi    NaN
2  John   92.0
3  Sara   88.0


### Handling Missing Values with fillna()

The `fillna()` function is used to replace missing values with a specified value.

For example, we can replace a missing mark with `0`.

In [16]:
clean_df["Marks"] = clean_df["Marks"].fillna(0)

print(clean_df)

   Name  Marks
0   Ali   85.0
1  Ravi    0.0
2  John   92.0
3  Sara   88.0


### Detecting Missing Values

We can use `isnull()` to identify missing values in a DataFrame.

In [17]:
print(clean_df.isnull())

    Name  Marks
0  False  False
1  False  False
2  False  False
3  False  False
